server:
  port: 8080
  forward-headers-strategy: framework

spring:
  # MVC
  web.resources.add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false

  # DB
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true

  # File Upload
  servlet:
    multipart:
      enabled: true
      location: "./src/main/resources/files/"
      max-file-size: "50MB"
      max-request-size: "50MB"

# API Docs
springdoc.swagger-ui:
  enabled: true
  path: /docs
  tags-sorter: alpha # 태그를 알파벳 순으로 정렬합니다.

# Security
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: "#{60 * 60 * 24}"

# AWS S3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region.static: ap-northeast-2
    s3.bucket: kakao-techcampus
    stack.auto: false